/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : ZINT
 #	author : miyako
 #	2016/04/19
 #
 # --------------------------------------------------------------------------------*/

#include "zint.h"
#include "png.h"
#include "zlib.h"
#include "font.h"
#include "maxipng.h"

// --- ZINT
void ZINT(sLONG_PTR *pResult, PackagePtr pParams);

#define ZINT_HEIGHT 1
#define ZINT_WHITE_SPACE 2
#define ZINT_BORDER 3
#define ZINT_BOX 4
#define ZINT_BIND 5
#define ZINT_SCALE 9
#define ZINT_ROTATE 10
#define ZINT_COLUMNS 11
#define ZINT_VERSION 12
#define ZINT_SECURE 13
#define ZINT_PRIMARY 14
#define ZINT_MODE 15
#define ZINT_GS1 16
#define ZINT_NO_TEXT 17
#define ZINT_SQUARE 18
#define ZINT_KANJI 19
#define ZINT_SJIS 20
#define ZINT_SMALL_TEXT 21
#define ZINT_DPI 22
#define ZINT_NO_BACKGROUND 23

#define ZINT_OUTPUT_SVG 1
#define ZINT_OUTPUT_PNG 2

#define INCHES_PER_METER (100.0/2.54)

void toSVG(zint_symbol *sym, int dpi, int rotate_angle, bool no_background, C_TEXT &_dump, sLONG_PTR *pResult);
void toPNG(zint_symbol *sym, int dpi, int rotate_angle, bool no_background, C_TEXT &_dump, sLONG_PTR *pResult);